Rahix/tbot

doc/getting-started.rst, doc/install.rst
Two minor documentation changes:
* There is a small example that shows how tests can be written without type annotations but it still contains a return type annotation which is not really required so I removed that as well.
* The other change is to use the public Github URL in the documentation instead of gitlab.denx.com which seems to require registration.
=> Documentation improvements

tbot/tc/uboot/build.py
When checking out U-Boot it use useful to allow checking out a particular
commit. Add support for this.
Signed-off-by: Simon Glass <sjg@chromium.org>
=> Allow specifying the revision to check out

Documentation/configuration.rst, Documentation/context.rst, Documentation/index.rst, Documentation/modules/main.rst, Documentation/modules/role.rst, Documentation/quickstart.rst, tbot/__init__.py, tbot/context.py, tbot/machine/board/board.py, tbot/machine/board/linux.py, tbot/machine/connector/common.py, tbot/machine/connector/connector.py, tbot/machine/connector/paramiko.py, tbot/machine/connector/ssh.py, tbot/machine/machine.py, tbot/main.py, tbot/role.py, tbot/selectable.py, tbot_contrib/connector/pyserial.py
The existing `tbot.selectable` module is a glorified hack for bridging between the selected config and the testcases.  As tbot aims to support more and more complex use-cases, it becomes apparent that this existing mechanism is not sufficient.
The "Context" is an attempt to solve this problem:  It is a central "machine manager" where the config registers available machine classes and testcases request instances from.  The idea is to have global management of instances so testcases need not concern themselves with creating and passing instances around.  Instead, the manager keeps the instances at the ready for any testcase that needs access.
A few quick examples:
```python
@tbot.testcase
def test_board_linux() -> None:
with tbot.ctx.request(tbot.role.BoardLinux) as lnx:
lnx.exec0("uname", …
```
=> Introduce "Context" mechanism for machine instance management

Documentation/modules/machine.rst, tbot/machine/__init__.py, tbot/machine/machine.py
Add pre-connection and post-shell initializer contexts, which run
before and after the existing Initializer context, for additional
flexibility.
Signed-off-by: Niel Fourie <lusus@denx.de>
=> machine: Add additional initializer contexts

tbot/context.py, tbot/machine/linux/ash.py
This series adds two more features to the `Context`s:
1. The `keep_alive` mode in which the `Context` keeps instances alive even after the last "user" exits.  This means follow-up `request()`s will get the "old" instance instead of having to initialize a new one.
2. The `reset_on_error` request-mode where an exception while the instance is life will trigger teardown of the instance.  In conjunction with `keep_alive` this is important to make sure an unrelated request later on will get clean instance, even if a failure occured during the earlier request.
=> Add more features to Context mechanism

.github/workflows/ci.yml, .pre-commit-config.yaml, selftest/conftest.py, selftest/mypy.ini, selftest/testmachines.py, selftest/tests/test_board.py, selftest/tests/test_channel.py, selftest/tests/test_context.py, selftest/tests/test_interactive_commands.py, selftest/tests/test_machine_basics.py, selftest/tests/test_path.py, selftest/tests/test_shell.py, stubs/pytest.pyi, tbot/machine/linux/ash.py, tbot/machine/linux/bash.py, tbot/machine/linux/path.py
Instead of the custom "test-framework", use [pytest](https://docs.pytest.org/en/stable/index.html) to run tbot's selftests.
I've used this opportunity to demonstrate integration of tbot into a pytest test-suite.  With the `keep_alive` and `reset_on_error` modes of `tbot.Context`, machines are only reset when a failure occurs or it was explicitly requested.  This is extremely useful when testing against real hardware which takes some time to reset.
=> Reimplement selftests with pytest

tbot/machine/connector/paramiko.py
the previous use leaves the file open for a while, triggering a
ResourceWarning. by using a context manager we avoid that problem.
Signed-off-by: Bernhard Kirchen <bernhard.kirchen@mbconnectline.com>
=> ParamikoConnector: close SSH config file

CHANGELOG.md, selftest/tests/test_path.py, tbot/machine/linux/path.py
This is a proposal to implement `unlink()` and `rmdir()` in `tbot.machine.linux.path.Path` to conveniently remove empty directories, symlinks and files from a host's filesystem using the shell commands `rmdir` and `rm`, respectively.
Tests were added/extended to assert reasonable behavior of the new methods.
The unlink method was equipped with a `missing_ok` parameter for compatibility to [`pathlib.Path.unlink()`](https://docs.python.org/3.8/library/pathlib.html#pathlib.Path.unlink).
Signed-off-by: Bernhard Kirchen <bernhard.kirchen@mbconnectline.com>
=> linux.Path: implement rmdir and unlink methods

CHANGELOG.md, tbot/machine/connector/paramiko.py
in case an error occurs while trying to parse the SSH config by paramiko or when looking up the config for a particular host, the respective warning now includes the exception's string representation with possibly helpful information about the problem.
in my case I had
`Warning: [...]/tbot/machine/connector/paramiko.py:168: UserWarning: Invalid .ssh/config`
which was not helping at all.
this on the other hand
`Warning: [...]/tbot/machine/connector/paramiko.py:168: UserWarning: Invalid .ssh/config: expected str, bytes or os.PathLike object, not IPv4Address`
helped me immediately. I set an `ipaddress.ip_address` as the hostname.
the gain is also apparent with actual parser problems (missing argument to `IdentityFile` in `~/.ssh/config`):
`Warning: …
=> ParamikoConnector: show SSH config parser error

CHANGELOG.md, Documentation/modules/machine_linux.rst, selftest/tests/test_shell.py, tbot/machine/linux/__init__.py, tbot/machine/linux/special.py
- implement the new classes, reusing _Stdio class for RedirBoth and
AppendBoth by adding a _both property and thus reducing code
duplication.
- add tests for RedirBoth and RedirStderr, which were previously not
covered.
- add tests covering the new classes
- add documentation for the new classes
- update changelog
=> machine.linux specials: add Append(Stdout|Stderr|Both)

selftest/testmachines.py, selftest/tests/test_path.py, tbot/machine/linux/path.py, tbot/tc/git.py
As discussed in #53, the `Path` class was in serious need of some refactoring.  This PR actions on the discussion:
1. Drop the inheritance from pathlib and instead reimplement the API surface manually.
2. By doing this, fix the broken inherited methods like e.g. `.relative_to()`
3. Introduce an `at_host(host)` method for cleanly converting a tbot-path to a string.
Cc: @schlimmchen
=> Refactor tbot's Path class

tbot/machine/linux/special.py
when redirecting stderr (2) to file descriptor 1 *before* redirecting stdout (1) to `/dev/null`, output to stderr will not be redirected to `/dev/null` as expected, but to stdout.
tests are hard to do for this, so I ended up not touchung the respective test in `test_shell.py`.
=> shell background jobs: redir stderr as expected

Documentation/contrib/gdb.rst, Documentation/index.rst, selftest/tests/contrib/test_gdb.py, tbot_contrib/gdb.py
Add a GDB machine to `tbot_contrib.gdb` which can be used for interacting with the GNU debugger interactively.
I wrote this some time ago but never got around to properly testing it and finalizing the implementation.  I'll keep it here for now; if anyone is interested in continuing work on this, feel free to do so!
=> WIP: GDB machine

tbot/machine/board/uboot.py, tbot/machine/channel/channel.py
Hello dev's,
we've using DEL (\x7f) as autoboot interrupt key as also in the [example](https://tbot.tools/modules/machine_board.html#tbot.machine.board.UBootAutobootIntercept), but we're getting the following exception:
```
├─Exception:
│   Traceback (most recent call last):
│     File "/mnt/work/dev/testrack/tbot/tbot/main.py", line 345, in main
│       func(**params)
│     File "/mnt/work/dev/testrack/tbot/tbot/decorators.py", line 62, in wrapped
│       return tc(*args, **kwargs)
│     File "/mnt/work/dev/testrack/tbot/tbot/tc/callable.py", line 50, in interactive_uboot
│       with tbot.ctx.request(tbot.role.BoardUBoot) as ub:
│     File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
│       return next(self.gen)
│     File "/mnt/work/dev/testrack/tbot/tbot/context.py", …
```
=> UBootAutobootIntercept: Allow all keys for autoboot interrupt

tbot_contrib/locking.py
Changed the permissions of the tbot machine lock and lock lock to
0666 to ensure all users can grab the locks.
Signed-off-by: Niel Fourie <lusus@denx.de>
=> contrib: locking: Change permissions of lock files

Documentation/contrib/uboot.rst, Documentation/index.rst, tbot/tc/uboot/testpy.py, tbot_contrib/uboot/__init__.py, tbot_contrib/uboot/_testpy.py
There exists previous integration for U-Boot's test/py testsuite in `tbot.tc.uboot`.  This implementation, however, has bitrotten quite some and does not work well with newer versions of tbot anymore - for some setups it fails to work at all.
The problem was that this old testcase aimed to be directly callable and for this it needs to figure out its environment on its own:  Where U-Boot sources are found, what U-Boot config to use, what board machine to use, etc.  This amount of "smart detection" made the testcase often too inflexible for adequate use.
Add a reworked test/py integration which instead provides only the mechanism to attach a tbot board-machine to a test/py invocation from an existing U-Boot source tree.  This mechanism should then be integrated into ones own calling …
=> Add reworked test/py integration

CHANGELOG.md, tbot/machine/board/__init__.py, tbot/machine/board/board.py, tbot/machine/board/linux.py
Add a new protocol for all machines which were "derived" from a `board.Board` at some point.  These should all implement the `BoardMachineBase` protocol which demands a `.board` property for accessing the original board.
This is useful because the `board.Board` machine might be used to define some parameters for this specific physical hardware, like an IP address. A `BoardUBoot` or `BoardLinux` machine would then want to be generic over these parameters.  To illustrate:
```python
class MyBoard(..., board.Board):
ip_address = "1.2.3.4"
@tbot.testcase
def foo_test():
with tbot.ctx.request(tbot.role.BoardUBoot) as ub:
ip_address = ub.board.ip_address
with tbot.ctx.request(tbot.role.BoardLinux) as lnx:
ip_address = lnx.board.ip_address
```
One could now define different configs with different …
=> machine.board: Introduce .board property

tbot/machine/board/uboot.py, tbot/machine/channel/channel.py, tbot/machine/linux/ash.py, tbot/machine/linux/bash.py, tbot/machine/shell.py, tbot_contrib/gdb.py
Let's follow systemd and use "`CTRL-]` three times within 1 second" as the universal escape sequence in tbot.  There are a number of reasons for this:
1. The old (undocumented) `~.` would conflict with ssh sessions which means you need to escape the escape sequence (= `~~.`) when trying to exit a tbot interactive session inside an ssh session.
2. Any key-sequence made up of commonly used characters is bound to conflict _somewhere_.  `CTRL-]` will most likely never show up in actual interaction and even less so as three consecutive presses.
`Channel.attach_interactive()` will now also print out a message instructing about this escape sequence.  This should make sure nobody will ever get stuck inside an interactive session again.
The old "`CTRL-D` to exit" behavior can be re-activated for …
=> channel: Implement new escape sequence

Documentation/contrib/utils.rst, Documentation/modules/machine_linux.rst, selftest/testmachines.py, selftest/tests/contrib/test_utils.py, selftest/tests/test_copy.py, tbot/machine/linux/__init__.py, tbot/machine/linux/copy.py, tbot/tc/shell.py, tbot_contrib/utils.py
The main purpose of the PR is adding the `copy_to_dir()` helper in `tbot_contrib.utils`.  This helper can be used to copy one or many files to a directory.  The copies will each have the same name as the respective source file.  `copy_to_dir()` will return the path(s) to the copies.
Under the hood, it uses `copy()` which was moved from `tc.shell` to `machine.linux` (although the old name still exists for compat).  This means that `copy_to_dir()` also works across SSH connections.
=> Move copy() into linux module and add a utils.copy_to_dir() helper to contrib

tbot/newbot.py
Signed-off-by: Mark A <mkand@microsoft.com>
resolves https://github.com/Rahix/tbot/issues/80
=> newbot: Add --log option to newbot CLI.

tbot/tc/shell.py
Hello @Rahix,
we have some test cases where we use `hashcmp()` excessively to ensure the device under test is in shape.
Add the parameter `use_cache`, which defaults to `False`, for optional cached results.
In the same test, we use check_for_tool() to determine if some executables/scripts need to be deployed first, but since the result of `check_for_tool()` is cached, we still always get `False` from `check_for_tool()` after a successful deployment.
Add the parameter `use_cache`, which defaults to `True`, to optionally disable cached results.
I have implemented the default values for `use_cache` to keep the old behavior of `check_for_tool()` and `hashcmp()`.
Greets, Johann
=> Add use_cache parameter to check_for_tool() and hashcmp()

tbot_contrib/connector/auto.py
The `AutoConsoleConnector` is a connector which will automatically select the best available tool to open a serial console.  The tbot user does not need to concern themselves with the specifics of each tool but can instead define generic settings which will be passed correctly to the chosen tool.
For now, the following tools are supported and selected in the order below:
- tio: https://github.com/tio/tio
- picocom: https://github.com/npat-efault/picocom
=> contrib: connector: Add AutoConsoleConnector

tbot/machine/connector/ssh.py
The previous attempt at fixing the special-casing of lab-host vs. local-host based connections in commit f9f2fe8a2512 ("connector: ssh: Fix contexts breaking ssh lab-host usecase") actually never worked as intended.
Fix it by using the proper subclass check.
Fixes: f9f2fe8a2512 ("connector: ssh: Fix contexts breaking ssh lab-host usecase")
=> connector: ssh: Fix connecting via lab-host for real

tbot/machine/board/linux.py
The expected value for password prompt was hardcoded ("assword: ") which results in an unability to login when the language is not set to English. This commit adds a new variable which is by default set to the previously hardcoded string, but allows the user to overwrite it on demand.
=> board.linux: Add pasword prompt variable

tbot/main.py, tbot/newbot.py
Make it possible to use shell environment vairiables in argumentfiles.
=> tbot/main.py: Allow Shell variables also in argumentfiles

tbot/machine/channel/subprocess.py
This fix is possibly related to the problem described in #94 by @yanivy-nr.
It happens from time to time that subprocess close() stalls forever. I guess the reason is a raise conditions when terminating the process and closing the piped streams.
A note in Python's [subprocess documentation](https://docs.python.org/3/library/subprocess.html) suggests to use following code snipped to properly terminate/kill a subprocess:
proc = subprocess.Popen(...)
try:
outs, errs = proc.communicate(timeout=15)
except TimeoutExpired:
proc.kill()
outs, errs = proc.communicate()
=> fix stalled subprocess close

selftest/tests/test_shell.py, tbot/error.py, tbot/machine/linux/ash.py, tbot/machine/linux/bash.py, tbot/machine/linux/util.py
Add a sanity check that ensures the shell on the remote end is really in the state we expect it to be in before we start interacting with it.
This check should uncover the following kinds of errors early:
- Heavy amounts of output clobbering from some source
- tbot tracking the wrong prompt (offset error)
- fancy shell configuration that tbot wasn't able to disable
Previously, such errors would only surface later, when trying to run commands.  The error messages were quite confusing and didn't immediately point to the root cause.  This sanity check should hopefully make debugging these issues much easier.
=> machine: linux: Add sanity check for shell interaction

tbot/machine/channel/subprocess.py
There were complaints that tbot would raise the "some subprocess(es) did not stop" error too quickly.  The previous 1.27s timeout was too short for some programs to exit on their own.
To make tbot more graceful, increase the maximum termination time to 10.2 seconds.  However, a warning will be emitted at 1.27s to let the user know why tbot is waiting.
Fixes: #116
Cc: @VictorEmelin
=> channel: Increase grace period for subprocesses to stop

selftest/testmachines.py, selftest/tests/test_board.py, tbot/machine/board/uboot.py, tbot/machine/channel/channel.py
The `crc32` command in U-Boot unfortunately prints the character sequence `=> ` as part of its output.  This character sequence is an often used U-Boot prompt, which means tbot's prompt-searching code gets confused by `crc32` output.
Unfortunately, there is no real solution to this.  At least none that works universally.  So to at least ease the pain a bit for people running into this, attempt automatically applying a workaround for this specific situation.
Closes #111.
=> machine: u-boot: Add a hacky workaround for the crc32 command
